name: DBA workflow - reusable

on:
  workflow_dispatch:
    inputs:
      instance:
        required: true
        default: 'test-3'
        type: string
      database_name:
        required: true
        type: string

jobs:
  call-reusable-workflow:
    name: "Create database"
    uses: aopopov90/cloudsql-dba-reusable-workflows/.github/workflows/create_database.yaml@develop
    with:
      project_number: "972321173961"
      workload_identity_pool: "gh-pool-4ga"
      workload_identity_provider: "gh-provider-4ga"
      service_account: "cloudsql-admin-sa@impactful-mode-268210.iam.gserviceaccount.com"
      cloudsql_instance: ${{ inputs.instance }}
      database_name: ${{ inputs.database_name }}
