name: DBA workflow - reusable

on:
  workflow_dispatch:
    inputs:
      instance:
        required: true
        default: 'test-1'
        type: string
      database_name:
        required: true
        type: string

jobs:
  call-reusable-workflow:
    name: "Create database"
    uses: aopopov90/cloudsql-dba-reusable-workflows/.github/workflows/create_database.yaml@develop
    with:
      project_number: ""
      workload_identity_pool: "gh-pool"
      workload_identity_provider: "gh-provider"
      service_account: ""
      cloudsql_instance: ${{ inputs.instance }}
      database_name: ${{ inputs.database_name }}
