name: Manual workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/972321173961/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@impactful-mode-268210.iam.gserviceaccount.com'
        
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'test'
      run: |-
        gcloud iam service-accounts list
